instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - name: bosh-bot
    properties:
      bosh:
        assets: ((bosh_bot_assets))
        deployments: ((bosh_bot_deployments))
        env: ((bosh_bot_env))
        password: ((bosh_bot_password))
        releases: ((bosh_bot_releases))
        stemcells: ((bosh_bot_stemcells))
        user: ((bosh_bot_user))
      slack:
        authorized_channels: ((bosh_bot_slack_authorized_channels))
        authorized_usernames: ((bosh_bot_slack_authorized_usernames))
        notification_channel: ((bosh_bot_slack_notification_channel))
        token: ((bosh_bot_slack_token))
    release: bosh-bot
  name: bosh-bot
  networks:
  - name: private
  stemcell: default
  vm_type: bot
name: bosh-bot
releases:
- name: bosh-bot
  sha1: ea7a4e2197f181aa9f620b04699c877a5daf2ce9
  url: https://storage.googleapis.com/bosh-bot-releases/bosh-bot-0.0.8.tgz
  version: 0.0.8
stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest
update:
  canaries: 1
  canary_watch_time: 1000-30000
  max_in_flight: 10
  update_watch_time: 1000-30000
