---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ljfranklin/bosh-bot

inputs:
  - name: bosh-bot
  - name: version

outputs:
  - name: created-release

run:
  path: bosh-bot/ci/tasks/create-release
