---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ljfranklin/bosh-bot

inputs:
  - name: bosh-bot
  - name: version
  - name: rc-release

outputs:
  - name: updated-bosh-bot
  - name: finalized-release

run:
  path: bosh-bot/ci/tasks/finalize-release

params:
  BLOBSTORE_ACCESS_KEY: ""
  BLOBSTORE_SECRET_ACCESS_KEY: ""
  BLOBSTORE_ENDPOINT: ""
  BLOBSTORE_REGION: ""
  GIT_USER_NAME: ""
  GIT_USER_EMAIL: ""
